### ISSUE TITLE
User Manual does not open from the toolbar

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#23]
Help->User Manual
Nothing happened
Version: Chem4Word 2022 Beta 1 - [3.2.1.8094]

**Comment by MikeWilliams-UK** [comment]
@tomyan112 I will look into this - I think I may have missed a file name change :-(

**Comment by MikeWilliams-UK** [comment]
In the mean time you can download the new manual from https://github.com/Chem4Word/Version3-2/blob/main/docs/Chem4Word-Version3-2-User-Manual.docx

**Comment by MikeWilliams-UK** [comment]
As I suspected - I forgot to update a constant for the new version

```csharp
const string fileNameOfManual = "Chem4Word-Version3-1-User-Manual.docx";
```

should have been changed to

```csharp
const string fileNameOfManual = "Chem4Word-Version3-2-User-Manual.docx";
```

This will be fixed in the next version

**Comment by MikeWilliams-UK** [comment]
Fixed and waiting on internal testing before deployment.

**Comment by MikeWilliams-UK** [comment]
Fixed in Beta 2
