### ISSUE TITLE
Most of the reation toolbar buttons are greyed out

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#24]
![image](https://user-images.githubusercontent.com/9064351/156179232-b3b8ecff-9e86-4e08-8787-ee4f4efcae81.png)

Are they not ready in this version?

**Comment by MikeWilliams-UK** [comment]
@deadlyvices can you please explain how to enable the buttons for @tomyan112

**Comment by deadlyvices** [comment]
The buttons won't be enabled unless you have a reaction selected. 
First, draw a reaction arrow using the reaction tool.
Then select it. 
You will see the buttons become enabled.
The reaction roles button will not be enabled until you have reactant(s), reaction *and* product selected.

It's not much help in that you don't have access to the new user manual yet. Hopefully all will become clear when you can read that.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices I have pointed out where @tomyan112 can download the manual direct from GitHub in #23
