### ISSUE TITLE
Not able to open the editor when only the reaction arrow is presence

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#25]
**Expected behavior**
Should open up the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/9064351/156226712-3f69035a-60d4-4b75-b520-c936159a866f.png)

**Comment by MikeWilliams-UK** [comment]
Thanks @tomyan112 I will attend to this.

**Comment by MikeWilliams-UK** [comment]
Fixed in Beta 2
