### ISSUE TITLE
New line instead of confirm when enter is pressed

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#28]
**Is your feature request related to a problem? Please describe.**
Would like to be able to create reaction condition in multiple line.
![image](https://user-images.githubusercontent.com/9064351/156317014-fd067ac6-ad34-4e1f-9a21-1eb6bf3fbb35.png)
![image](https://user-images.githubusercontent.com/9064351/156317253-42f6de90-13c4-4627-a6ef-80a30dcde4be.png)

**Comment by MikeWilliams-UK** [comment]
@tomyan112 you can use Shift + Return to add a line feed.
@deadlyvices was this not in the manual?

**Comment by tomyan112** [comment]
First I type 
![image](https://user-images.githubusercontent.com/9064351/156320445-66843e34-4802-4f90-bf17-3daf5f2cf271.png)
in two line
then I copy and paste to
![image](https://user-images.githubusercontent.com/9064351/156320339-f747573e-8068-4a1e-8488-f08f93ff237c.png)
Only first line is rendered.
![image](https://user-images.githubusercontent.com/9064351/156320618-ccaada6f-dac9-4855-87ca-3719374aac8b.png)

**Comment by deadlyvices** [comment]
I'll add the instruction to use [Shift]-[Return] to the manual (It's displayed on the status bar, by the way!)

Are you cutting and pasting the original text from Word into the editor?

**Comment by tomyan112** [comment]
> 

Yes, I was cutting and pasting the original text from Word into the editor.

**Comment by deadlyvices** [comment]
Don't do that! :-)

**Comment by MikeWilliams-UK** [comment]
@deadlyvices I am re-opening this issue as Chem4Word is a chemical editor for Word it should accept and cope with paragraphs copied and pasted from Word.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices Pasting plain text from notepad++ also exhibits the same bad behaviour, so this is not Word specific.
![image](https://user-images.githubusercontent.com/13162784/156390826-af2906e0-922d-4da6-8e43-8872af2ed158.png)
Copy the above, then paste into editor, which shows as
![image](https://user-images.githubusercontent.com/13162784/156391106-3f272ae8-8c9f-45c5-aec1-5944b1f6dd35.png)
Then saves as
![image](https://user-images.githubusercontent.com/13162784/156391250-2f57b5f1-9c88-4ace-b8c5-c70687969c26.png)

**Comment by MikeWilliams-UK** [comment]
@deadlyvices @tomyan112 this is now fixed, awaiting testing and release at which point the issue will be closed.

**Comment by MikeWilliams-UK** [comment]
Fixed in Beta 2
