### ISSUE TITLE
Problem of calculating the valence electrons

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#30]
**Describe the bug**

The editor keeps adding hydrogen when the −ve charge is increasing in order to keep the valence electron the same.

**Current behavior**
![image](https://user-images.githubusercontent.com/9064351/156888000-25bd5f21-80d6-4a45-939b-351724c5efb8.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/9064351/156888125-a22fabec-bd16-49cc-a8ae-a4cdbd4e7c5c.png)
with the red circle indicating there is an error in valence count 
![image](https://user-images.githubusercontent.com/9064351/156888167-a2740c0a-56d7-4578-a696-53e5d438fa70.png)

**Comment by tomyan112** [comment]
By current design, acetylide ion can't be drawn
**Current design**
![image](https://user-images.githubusercontent.com/9064351/156897138-23f87d6e-6304-475e-9895-4f48584f4d73.png)


**Acetylide ion**
![image](https://user-images.githubusercontent.com/9064351/156897118-6dd645be-39ef-4f86-b90b-c0f54cb7c826.png)

**Comment by deadlyvices** [comment]
This is a serious bug and needs to be fixed ASAP.
@MikeWilliams-UK  please create a bug item for this

**Comment by MikeWilliams-UK** [comment]
Included in V3.2.3 Beta 3
