### ISSUE TITLE
Can't see the bond after changing the hydrogen placement

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#32]
**Describe the bug**
Can't see the bond after changing the hydrogen placement

**To Reproduce**
1. 
![image](https://user-images.githubusercontent.com/9064351/156893498-3ee6cec1-6269-4a90-bc13-fb46dae21b59.png)
2.
![image](https://user-images.githubusercontent.com/9064351/156893505-54325135-4581-4292-b720-5f0b849cc8bc.png)
3.
![image](https://user-images.githubusercontent.com/9064351/156893525-4b322132-6b81-402f-8160-20463af8b64e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/9064351/156893591-47e8f5b3-4dab-471d-a1f3-dce5e4329395.png)

Edit: Add markdown to format cml properly
**CML Data**
```xml
<cml:cml xmlns:conventions="http://www.xml-cml.org/convention/" xmlns:cml="http://www.xml-cml.org/schema" xmlns:cmlDict="http://www.xml-cml.org/dictionary/cml/" xmlns:nameDict="http://www.xml-cml.org/dictionary/cml/name/" xmlns:c4w="http://www.chem4word.com/cml" conventions="convention:molecular">
  <c4w:customXmlPartGuid>3f0f6e68835b4b109cd05b2a60633116</c4w:customXmlPartGuid>
  <cml:molecule id="m1">
    <cml:formula id="m1.f0" concise="C 2 H 4" />
    <cml:formula id="m1.f1" convention="chem4word:ResolvedFormula" inline="C2H4" concise="C 2 H 4" />
    <cml:formula id="m1.f2" convention="chem4word:ResolvedSmiles" inline="C=C" concise="C 2 H 4" />
    <cml:name id="m1.n1" dictRef="chem4word:CalculatedInchi">1S/C2H4/c1-2/h1-2H2</cml:name>
    <cml:name id="m1.n2" dictRef="chem4word:CalculatedInchikey">VGGSQFUCUMXWEO-UHFFFAOYSA-N</cml:name>
    <cml:name id="m1.n3" dictRef="chem4word:ResolvedIupacname">ethene</cml:name>
    <cml:atomArray>
      <cml:atom id="a1" elementType="C" x2="429.25" y2="563.5" c4w:hydrogenPlacement="East" />
      <cml:atom id="a2" elementType="C" x2="459.25" y2="563.5" />
    </cml:atomArray>
    <cml:bondArray>
      <cml:bond id="b1" atomRefs2="a1 a2" order="D" />
    </cml:bondArray>
  </cml:molecule>
</cml:cml>
```

**Comment by MikeWilliams-UK** [comment]
This will be due to the clipping algorithm removing parts of the bond lines which the H2 characters are obscuring.

Solution is to either make the bond longer or set the H to anything other than "E"ast on the left most Carbon atom.

Colsing as this is by design.
