### ISSUE TITLE
Size of reaction arrow and molecule does not change when there is no bond

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#35]
1.
![image](https://user-images.githubusercontent.com/9064351/156907856-5690c878-ca85-45e2-99d5-501e24dc08d9.png)
2.
![image](https://user-images.githubusercontent.com/9064351/156907879-4936970d-31a5-4a86-a992-55cf188fbcfb.png)
Fail
![image](https://user-images.githubusercontent.com/9064351/156908006-a7cc47ff-ff88-443c-a94c-aa96c7e80d57.png)

Success
![image](https://user-images.githubusercontent.com/9064351/156907915-9228abc8-6cb1-466b-b94b-28d610da4026.png)

**Desktop (please complete the following information):**
Chem4Word beta 2

**Comment by deadlyvices** [comment]
I've done some fixes to this, but the problem remains that if you have a model with no molecules then the average bond length will be zero. The rescaling calculation is based on this parameter. 
This means that it will rescale properly if molecules are present but won't if all you have is a reaction arrow. As I think that the latter is very much an edge case I propose to leave it with the changes I have added.

**Comment by MikeWilliams-UK** [comment]
Included in V3.2.3 Beta 3
