### ISSUE TITLE
Avoid clipping of multiple bond

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#37]
**Is your feature request related to a problem? Please describe.**
Currently, the bond would just overlap each other which would mean there is an ambiguity to interpret as another compound.
Compound in this example is cyclooctatetraene in its native "tub-shaped" conformation
![image](https://user-images.githubusercontent.com/9064351/157187391-96c4fe4f-9e72-4e56-852b-ea4eabeefcab.png)
![image](https://user-images.githubusercontent.com/9064351/157187460-18706bfe-c3a2-43fa-b500-0f698fd0f99d.png)

**Describe the solution you'd like**
A little gap would appear to avoid overlap
![1280px-All-Z-Cyclooctatetraene_3D_skeletal_formula svg](https://user-images.githubusercontent.com/9064351/157187518-b0c94182-388e-49ec-bede-37d7cfff6542.png)

**Comment by MikeWilliams-UK** [comment]
Included in V3.2.3 Beta 3
