### ISSUE TITLE
Cannot install the program

### ISSUE THREAD

**Issue by Matu-SK** [Chem4Word/Version3-2#44]
**Description**
The program fails to install.

**Screenshots**
<img width="857" alt="installation_windows" src="https://user-images.githubusercontent.com/54185663/218566538-4451dc07-4b3f-4f50-b913-458a0e1e3ec9.png">
<img width="368" alt="error_message" src="https://user-images.githubusercontent.com/54185663/218566565-3bf4db8e-b512-4136-8f95-badda64c7ec1.png">
<img width="475" alt="installation_error_window" src="https://user-images.githubusercontent.com/54185663/218566480-cf64edc1-09d0-48bf-8cf7-ae39acff980c.png">

**Desktop**
 - OS: Windows 11 Pro
 - Word Version: Microsoft 365 (Version 2301 Build 16.0.16026.20002 64-bit)

**Comment by MikeWilliams-UK** [comment]
Please can you disable your anti virus system temporarily and try again, we have seen some systems falsely detecting our installer as a virus.
