### ISSUE TITLE
Error occurs after editing a structure next to an equation

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#46]
**Describe the bug**
I get the following error after editing a structure wich is next to an equation.

**Screenshots**
![image](https://user-images.githubusercontent.com/9064351/72663154-1bf06c00-3a2a-11ea-8889-c4215797b534.png)

**Comment by deadlyvices** [comment]
This issue is no longer relevant. ACME has built in chemical reaction functionality so there is no longer any need to juxtapose structures and equations.
