### ISSUE TITLE
Chem4Word ribbon greyed out (except Options and Help) when opeing word document in compatability mode.

### ISSUE THREAD

**Issue by AntonyMasefield** [Chem4Word/Version3-2#47]
Having added some downloaded structures to a word document, via chem4word, when I reopened the document a few days later, when I open the Chem4word ribbon all the features are 'greyed out' except for the "Options and "Help" buttons.

If I open a new, blank, Word Document then the Chem4Word ribbon is active.

**To Reproduce**
Open saved document with Chem4Word structures embedded and the chemistry tab ribbon is inactive.

**Expected behavior**
Chemistry ribbon should be active

**Screenshots** 
![image](https://github.com/Chem4Word/Version3-2/assets/156896148/923f2c9d-088e-4f58-836d-1025bdd2a33e)

**Comment by MikeWilliams-UK** [comment]
@AntonyMasefield Can you please select the menu option "Help" --> "Buttons Disabled ..."
This will tell us the reason why.

**Comment by MikeWilliams-UK** [comment]
@AntonyMasefield Please also include the Word Title bar in your screen shot as this gives us extra information.

**Comment by AntonyMasefield** [comment]
Can't see the wood for the trees....
The file was in compatibility mode. No idea how that happened, it may have happened when I converted the original to a Word.HTML file.
Removed the compatibility mode and now it's fine.

I'm new to using Chem4Word so still finding my way around.

Sorry for bothering you.

Thanks Mike.

**Comment by MikeWilliams-UK** [comment]
No problem, glad we were able to sort out the issue quickly.

**Comment by MikeWilliams-UK** [comment]
PS: We disable the buttons in compatability mode because Microsoft have decided that some of the functions which we use to insert the structures are not available in this mode.
