### ISSUE TITLE
Unable to delete structures from Library.db

### ISSUE THREAD

**Issue by AntonyMasefield** [Chem4Word/Version3-2#48]
Opening the library displays structures but there is no 'X' to delete the structure, in the bottom left hand corner.
![image](https://github.com/Chem4Word/Version3-2/assets/156896148/39d6fdb4-3777-4c5d-8b51-f5a8922ed0dc)

Thanks
Tony

**Comment by Wydna** [comment]
Hi Tony,
To edit the library, you need to use the library editor.  You can access that from the Chem4Word Settings window.
![image](https://github.com/Chem4Word/Version3-2/assets/3438413/3815834e-2357-437d-8070-7d645000ea38)

![image](https://github.com/Chem4Word/Version3-2/assets/3438413/81bc3b00-7f0c-4be3-97bb-62b57a73c39c)

Andy

**Comment by Wydna** [comment]
Hi Tony,

We need to get you early access to version 3.3, currently in Beta, which has a library editor and the ability to easily create and edit multiple libraries.

Andy

**Comment by MikeWilliams-UK** [comment]
@AntonyMasefield can you please confirm that you are using V3.2 as the X button to delete a structure from the default library should still be present.

**Comment by AntonyMasefield** [comment]
Hi Andy,

 

Thanks for your rapid response. 

I was still using release 10, just upgraded to release 11 (as per the ‘Check for updates’ button’ in ‘Help’. and the Chemistry tab looks like this:

 



 



 

 

Options:

 



 

Same as version 10

 

Seems that I should be using the new ‘beta Version 3.3 to get access to the library.

 

BTW, thanks for producing this software, I’m finding it very useful indeed.

Wish it had been available years ago!

 

Regards,

Tony

**Comment by MikeWilliams-UK** [comment]
@AntonyMasefield the last comment has missing images (probably due to responding be email)

**Comment by MikeWilliams-UK** [comment]
Thanks for reporting this @AntonyMasefield - The ability to delete structures from V3.2 default library has indeed been lost.
I will look into restoring it.

**Comment by MikeWilliams-UK** [comment]
@AntonyMasefield - Sneak preview of the bug fix in our internal repository

![image](https://github.com/Chem4Word/Version3-2/assets/13162784/2cb09867-8ef4-4c5a-afeb-bb587a66adf7)
- Dropdown has been removed as it's useless. This was a V3.3 feature that somehow crept in :-)
- Dialog pops up to confirm delete of structure is required.

**Comment by MikeWilliams-UK** [comment]
> Wish it had been available years ago! 

@AntonyMasefield 
Chem4Word has been available since 2010, you simply did not know it existed.

See here https://www.chem4word.co.uk/history/

**Comment by AntonyMasefield** [comment]
Hi Mike,
I can confirm that the 'delete' library function was not there in release 10 or release 11.
I did chemistry/geology majors in 1971-1973 and chemistry honours in 1974.We didn't even have computers in those days!One of the projects in honours year phys chem was to enter data into the mainframe in the electrical eng./computer science building. The mainframe took up basically the whole top floor with only a small area for the system operator, a dot matrix printer, a card reader and a number of card punchers.
Otherwise, yes, working in industry one seldom uses chemical structures unfortunately.Now I'm working as a consultant ('polymer chemist' - primarily solvent based) and putting together a website which has some chemistry involved.
Thanks for your responses.
Cheers,Tony
    On Wednesday, 24 January 2024 at 15:41:41 GMT+2, Mike Williams ***@***.***> wrote:  
 
 



Wish it had been available years ago!


@AntonyMasefield
Chem4Word has been available since 2010, you simply did not know it existed.

See here https://www.chem4word.co.uk/history/

**Comment by MikeWilliams-UK** [comment]
@AntonyMasefield - I have just done some investigation and the delete button got "lost" in the first beta of V3.2 (V3.2.1) which was released on 28th February 2022.
I am truly astonished that you are the first to notice this.

Good luck with your consultancy. Feel free to email us at info@chem4word.co.uk or post in our Facebook group at https://www.facebook.com/groups/chem4word.

**Comment by MikeWilliams-UK** [comment]
Chem4Word 2022 - Release 12 (V3.2.17) has been released which fixes this bug
Please use "Help" -> "Check for Updates" to force a check now instead of within the next 7 days.
