### ISSUE TITLE
Allow the creation of multiple libraries in addition to 'Library.db'

### ISSUE THREAD

**Issue by AntonyMasefield** [Chem4Word/Version3-2#49]
Chem4Word /library/open has only one choice for the library to open - library.db.

In order to separate various structures from one type to another, it would be advantageous to have the ability to choose one or other library to open rather than the 'pre-set' 'library.db'.
For instance, the ability to create new database files and give them their own names:
organic_acids.db
organic_bases.db 
etc.
The databases could all be kept in the same folder as the 'library. db' database, so there's no real need to go to special lengths to make other folders 'selectable' - just a simple 'drop-down', as per the existing program, but with additional choices of databases.

**Comment by MikeWilliams-UK** [comment]
Please switch to version 3.3 beta, which can be downloaded from https://github.com/Chem4Word/Version3-3/releases
V3.3 allows the creation of multiple libraries

**Comment by MikeWilliams-UK** [comment]
Closing as this ability exists in V3.3
